schedules:
# Run from Monday to Friday at 5:30 UTC (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#cron-syntax)
- cron: "30 5 * * 1-5"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

trigger:
- master

pool: '.Net Bubble - GCP'

variables:
  - group: sonarsource-build-variables
  - name: isReleaseBranch
    value: ${{ or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/branch-')) }}
  - name: isBugFix
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/branch-') }}
  - name: system.debug
    value: true


stages:
- stage: debug
  displayName: Debug
  jobs:
    - job: print
      displayName: 'Print variables'

      steps:
      - powershell: Write-Host "IsBugFix: $(isBugFix), IsReleaseBranch: $(isReleaseBranch)"

      - powershell: Write-Host "A"
        condition: eq(variables.isReleaseBranch, 'True')

      - powershell: Write-Host "B"
        condition: eq(variables.isReleaseBranch, 'True')

      - powershell: Write-Host "C"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/branch-')
