# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: sonarsource-build-variables
  - name: solution
    value: 'sonaranalyzer-dotnet/SonarAnalyzer.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages
  - name: MSBUILD_PATH
    value: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe'
# MVN vars
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  - name: commonMavenArguments
    value: -B -Pdeploy-sonarsource -Dmaven.test.skip=true

resources:
  repositories:
    - repository: commonTemplates
      type: git
      name: pipelines-yaml-templates
      ref:  refs/tags/v1.0.6

steps:
- task: NuGetToolInstaller@1
  displayName: "Install NuGet"

- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: $(NUGET_PACKAGES)
  displayName: Cache NuGet packages

- task: NuGetCommand@2
  displayName: "Restore NuGet packages"
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
   # Calculate the file path
   $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\scripts\version\Version.props"
   Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."

   # Read the version from the file
   [xml]$versionProps = Get-Content "$versionFilePath"
   $sonarProjectVersion = $versionProps.Project.PropertyGroup.MainVersion
   Write-Host "Sonar project version is '${sonarProjectVersion}'"

   # Set the variable to it can be used by other tasks
   Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"
  displayName: 'Read Sonar project version from the versions.props file'

- task: VSBuild@1
  displayName: 'Set BranchName, Sha1 and BuildNumber properties from Azure pipeline variables'
  inputs:
    solution: scripts/version/ChangeVersion.proj
    msbuildArgs: '/p:Sha1=$(Build.SourceVersion) /p:BranchName=$(Build.SourceBranchName) /p:BuildNumber=$(Build.BuildId) /p:BuildConfiguration=$(BuildConfiguration)'

- task: DownloadSecureFile@1
  displayName: 'Download snk file'
  name: snk
  inputs:
    secureFile: SonarSourceSecret.snk

- task: DownloadSecureFile@1
  displayName: 'Download pfx file'
  inputs:
    secureFile: 'sonarsource-2019-2021.pfx'

- task: SonarCloudPrepare@1
  condition: false
  displayName: 'Run Code Analysis - Begin Step'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'sonarsource'
    scannerMode: 'MSBuild'
    projectKey: 'sonaranalyzer-dotnet'
    projectName: 'SonarAnalyzer .Net'
    projectVersion: '$(SONAR_PROJECT_VERSION)'
    extraProperties: 

- task: VSBuild@1
  displayName: "Build SonarAnalyzer"
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:DeployExtension=false /p:SignAssembly=true /p:DefineConstants=SignAssembly /p:AssemblyOriginatorKeyFile="$(snk.secureFilePath)" /p:pfxCertificatePath="$(pfx.secureFilePath)" /p:pfxPassword="$(pfxPassword)" /p:pfxSha1=$(pfxSha1) /p:Sha1=$(Build.SourceVersion) /p:BuildNumber=$(Build.BuildId)  '

- task: VSTest@2
  condition: false
  displayName: "Run SonarAnalyzer unit tests"
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\**\*.UnitTest.dll
     !**\obj\**
    runInParallel: true
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    rerunFailedTests: false

- task: SonarCloudAnalyze@1
  condition: false
  displayName: 'Run Code Analysis - End Step'

- task: SonarCloudPublish@1
  condition: false
  displayName: 'Run Code Analysis - Publish QG'
  inputs:
    pollingTimeoutSec: '300'

- task: NuGetCommand@2
  displayName: "Build NuGet packages"
  condition: false
  inputs:
    command: pack
    packagesToPack: 'sonaranalyzer-dotnet/src/**/*.nuspec'
    configuration: '$(BuildConfiguration)'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    verbosityPack: 'Detailed'
    publishPackageMetadata: true

- task: ArtifactoryNuGet@1
  condition: false
  displayName: "Publish NuGet packages"
  inputs:
    command: 'push'
    artifactoryService: 'Repox'
    targetDeployRepo: 'sonarsource-nuget-public'
    pathToNupkg: '$(Build.ArtifactStagingDirectory)\*.nupkg'

- task: PowerShell@2
  condition: false
  displayName: 'Run integration tests'
  inputs:
    filePath: 'sonaranalyzer-dotnet/its/regression-test.ps1'
    workingDirectory: 'sonaranalyzer-dotnet/its'

######### MVN stuff ########

- task: Cache@2
  displayName: "Cache Maven local repo"
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)

- task: DownloadSecureFile@1
  displayName: 'Download Maven settings'
  name: mavenSettings
  inputs:
    secureFile: 'maven-settings.xml'

- template: update-maven-version-steps.yml@commonTemplates
  parameters:
    mavenSettingsFilePath: $(mavenSettings.secureFilePath)

- task: Maven@3
  displayName: 'Run Maven deploy'
  condition: false
  env:
    ARTIFACTORY_DEPLOY_USERNAME: $(ARTIFACTORY_DEPLOY_USERNAME)
    ARTIFACTORY_DEPLOY_PASSWORD: $(ARTIFACTORY_DEPLOY_PASSWORD)
  inputs:
    goals: 'deploy'
    options: >-
      $(commonMavenArguments)
      --settings $(mavenSettings.secureFilePath)
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenOptions: $(MAVEN_OPTS)

# running UTs can be done in parallel with deploying
- task: Maven@3
  displayName: 'Run Maven verify'
  inputs:
    goals: 'verify'
    options: '-B --settings $(mavenSettings.secureFilePath)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'UTs on Windows'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenOptions: $(MAVEN_OPTS)

- template: prepare-sq-analysis-steps.yml@commonTemplates

# running SQ analysis can be done either in parallel or merged with running UTs
- task: Maven@3
  displayName: 'Run Maven verify with SQ'
  inputs:
    goals: 'verify'
    options: -B --settings $(mavenSettings.secureFilePath) -Pcoverage
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenOptions: $(MAVEN_OPTS)
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- bash: git checkout .
  name: revertPomChanges
  displayName: Revert changes made to pom.xml to not break cache feature

######### END MVN stuff ########
