schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

trigger:
- master

pool: '.Net Bubble - GCP'

variables:
  - group: sonar-dotnet-variables-tmp
  - group: sonarsource-build-variables

resources:
  repositories:
    - repository: commonTemplates
      type: git
      name: pipelines-yaml-templates
      ref:  refs/tags/v1.0.11

stages:
- template: stage-with-burgr-notifications.yml@commonTemplates
  parameters:
    burgrName: 'build'
    burgrType: 'build'
    stageName: 'build'
    # Build the dotnet analyzers and stage to repox
    stageDisplayName: 'Build:'
    jobs:
    - job: dotnetBuildjob
      displayName: 'Build and package'

      steps:
      - task: NuGetToolInstaller@1
        displayName: "Install NuGet"

      - task: NuGetCommand@2
        displayName: "Restore NuGet packages"
        inputs:
          restoreSolution: '$(solution)'
          feedsToUse: 'config'
          nugetConfigPath: 'analyzers\NuGet.Config'

      - powershell: |
          # Calculate the file path
          $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\scripts\version\Version.props"
          Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."

          # Read the version from the file
          [xml]$versionProps = Get-Content "$versionFilePath"
          $sonarProjectVersion = $versionProps.Project.PropertyGroup.MainVersion
          Write-Host "Sonar project version is '${sonarProjectVersion}'"

          # Set the variable to it can be used by other tasks
          Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"
        displayName: 'Read Sonar project version from the versions.props file'

      - powershell: |
          cd analyzers
          $testProjFileName = "tests\SonarAnalyzer.UnitTest\SonarAnalyzer.UnitTest.csproj"

          Write-Host "Remove .Net 5 target for UnitTest project"

          ((Get-Content -Path $testProjFileName -raw) -Replace "net48;net5.0","net48") | Set-Content -Path $testProjFileName

          Write-Host "Show test project after we modified the target frameworks to exclude net5"
          Get-Content -Path $testProjFileName

          cd ..
        displayName: 'Exclude net5 from the main build'

      - task: VSBuild@1
        displayName: 'Set BranchName, Sha1 and BuildNumber'
        inputs:
          solution: scripts/version/ChangeVersion.proj
          msbuildArgs: '/p:Sha1=$(Build.SourceVersion) /p:BranchName=$(Build.SourceBranchName) /p:BuildNumber=$(Build.BuildId) /p:BuildConfiguration=$(BuildConfiguration)'

      - task: DownloadSecureFile@1
        displayName: 'Download snk file'
        name: snk
        inputs:
          secureFile: SonarSourceSecret.snk

      - task: DownloadSecureFile@1
        displayName: 'Download pfx file'
        name: pfx
        inputs:
          secureFile: 'sonarsource-2019-2021.pfx'

      - task: VSBuild@1
        displayName: "Build and sign SonarAnalyzer solution"
        env:
          SIGNTOOL_PATH: 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.17763.0\\x64\\signtool.exe'
          PFX_PASSWORD: $(pfxPassword)
          PFX_PATH: $(pfx.secureFilePath)
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          msbuildArgs: '/p:DeployExtension=false /p:SignAssembly=true /p:AssemblyOriginatorKeyFile="$(snk.secureFilePath)" /p:Sha1=$(Build.SourceVersion) /p:BuildNumber=$(Build.BuildId) /p:WarningLevel=0'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish analyzer binaries as pipeline artifact'
        inputs:
          path: analyzers/its/binaries/
          artifact: Binaries

      - task: PublishPipelineArtifact@1
        displayName: 'Publish rule descriptor binaries as pipeline artifact'
        inputs:
          path: analyzers\src\SonarAnalyzer.RuleDescriptorGenerator\bin
          artifact: RuleDescriptorBin

      - task: NuGetCommand@2
        displayName: "Build NuGet packages"
        inputs:
          command: pack
          packagesToPack: 'analyzers/src/**/*.nuspec'
          configuration: '$(BuildConfiguration)'
          packDestination: '$(Build.ArtifactStagingDirectory)/packages'
          verbosityPack: 'Detailed'
          publishPackageMetadata: true

      - task: NuGetCommand@2
        displayName: "Sign NuGet packages"
        inputs:
          command: 'custom'
          arguments: 'sign $(Build.ArtifactStagingDirectory)\packages\*.nupkg -CertificatePath $(pfx.secureFilePath) -CertificatePassword $(pfxPassword) -Timestamper http://sha256timestamp.ws.symantec.com/sha256/timestamp'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish NuGet packages as build artifacts'
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
          artifactName: 'NuGet Packages'

      - task: ArtifactoryNuGet@1
        displayName: 'Publish SonarAnalyzer.CFG.CSharp NuGet on repox'
        inputs:
          command: 'push'
          artifactoryService: 'Repox artifactory'
          targetDeployRepo: '$(ARTIFACTORY_NUGET_REPO)'
          pathToNupkg: '$(Build.ArtifactStagingDirectory)/packages/SonarAnalyzer.CFG.CSharp.*.nupkg'

- template: stage-with-burgr-notifications.yml@commonTemplates
  parameters:
    burgrName: 'qa'
    burgrType: 'qa'
    stageName: 'qa'
    # .NET analyzers UTs, ITs, build Java and publish SC QG
    stageDisplayName: 'Tests:'
    stageDependencies: build

    jobs:
    - job: runUnitTestsJob
      displayName: '.NET UTs'

      steps:
      - task: NuGetToolInstaller@1
        displayName: "Install NuGet"

      - powershell: |
          # Calculate the file path
          $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\scripts\version\Version.props"
          Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."

          # Read the version from the file
          [xml]$versionProps = Get-Content "$versionFilePath"
          $sonarProjectVersion = $versionProps.Project.PropertyGroup.MainVersion
          Write-Host "Sonar project version is '${sonarProjectVersion}'"

          # Set the variable to it can be used by other tasks
          Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"
        displayName: 'Read Sonar project version from the versions.props file'

      - task: VSBuild@1
        displayName: 'Set BranchName, Sha1 and BuildNumber properties from Azure pipeline variables'
        inputs:
          solution: scripts/version/ChangeVersion.proj
          msbuildArgs: '/p:Sha1=$(Build.SourceVersion) /p:BranchName=$(Build.SourceBranchName) /p:BuildNumber=$(Build.BuildId) /p:BuildConfiguration=$(BuildConfiguration)'

      - task: SonarCloudPrepare@1
        displayName: 'Code Analysis - Begin (PR)'
        condition: eq(variables['Build.Reason'], 'PullRequest')
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'sonarsource'
          scannerMode: 'MSBuild'
          projectKey: 'sonaranalyzer-dotnet'
          projectName: 'SonarAnalyzer .Net'
          projectVersion: '$(SONAR_PROJECT_VERSION)'
          extraProperties: |
            sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)/**/coverage.**.xml"
            sonar.analysis.buildNumber=$(Build.BuildId)
            sonar.analysis.pipeline=$(Build.BuildId)
            sonar.analysis.sha1=$(System.PullRequest.SourceCommitId)
            sonar.analysis.prNumber=$(System.PullRequest.PullRequestNumber)
            sonar.analysis.repository=$(Build.Repository.ID)

      - task: SonarCloudPrepare@1
        displayName: 'Code Analysis - Begin (master or branch)'
        condition: ne(variables['Build.Reason'], 'PullRequest')
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'sonarsource'
          scannerMode: 'MSBuild'
          projectKey: 'sonaranalyzer-dotnet'
          projectName: 'SonarAnalyzer .Net'
          projectVersion: '$(SONAR_PROJECT_VERSION)'
          extraProperties: |
            sonar.cs.opencover.reportsPaths="$(Build.SourcesDirectory)/**/coverage.**.xml"
            sonar.analysis.buildNumber=$(Build.BuildId)
            sonar.analysis.pipeline=$(Build.BuildId)
            sonar.analysis.sha1=$(Build.SourceVersion)
            sonar.analysis.repository=$(Build.Repository.ID)

      - powershell: |
          . .\scripts\utils.ps1
          cd analyzers

          $testProjFileName = "tests\SonarAnalyzer.UnitTest\SonarAnalyzer.UnitTest.csproj"

          Write-Host "Show test project"
          Get-Content -Path $testProjFileName

          Write-Host "Build UnitTest project"
          & dotnet build $testProjFileName -c $(BuildConfiguration)
          Test-ExitCode "ERROR: UnitTest project build FAILED."

          $supportedFrameworks = @('net48', 'net5.0')

          Foreach ($framework in $supportedFrameworks)
          {
            & OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test $testProjFileName --no-build -c $(BuildConfiguration) -f $framework" -returntargetcode -filter:"+[SonarAnalyzer.CFG]* +[SonarAnalyzer]* +[SonarAnalyzer.CSharp]* +[SonarAnalyzer.Utilities]* +[SonarAnalyzer.VisualBasic]*" -output:tests\coverage.$framework.xml -oldStyle
            Test-ExitCode "ERROR: Unit tests for $framework FAILED."
          }

          cd ..
        displayName: '.Net UTs'

      - task: SonarCloudAnalyze@1
        displayName: 'Code Analysis - End'

      - task: SonarCloudPublish@1
        displayName: 'Code Analysis - Publish QG'
        inputs:
          pollingTimeoutSec: '300'

    - job: runIntegrationTestsJob
      displayName: '.NET ITs'
      workspace:
        clean: all
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download binaries to test'
        inputs:
          artifact: Binaries
          targetPath: 'analyzers/its/binaries/'

      - task: NuGetToolInstaller@1
        displayName: "Install NuGet"

      - task: PowerShell@2
        displayName: 'Run ITs'
        inputs:
          filePath: 'analyzers/its/regression-test.ps1'
          workingDirectory: 'analyzers/its'

    - job: runJavaBuild
      displayName: 'Java build'
      workspace:
        clean: all
      steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download .Net binaries for Maven build'
        inputs:
          artifact: Binaries
          targetPath: 'analyzers/src/SonarAnalyzer.Vsix/bin/$(buildConfiguration)/'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download rule descriptor binaries'
        inputs:
          artifact: RuleDescriptorBin
          targetPath: analyzers\src\SonarAnalyzer.RuleDescriptorGenerator\bin

      - task: DownloadSecureFile@1
        displayName: 'Download Maven settings'
        name: mavenSettings
        inputs:
          secureFile: 'maven-settings.xml'

      - template: update-maven-version-steps.yml
        parameters:
          mavenSettingsFilePath: $(mavenSettings.secureFilePath)

      - task: Maven@3
        displayName: 'Maven deploy'
        env:
          ARTIFACTORY_DEPLOY_USERNAME: $(ARTIFACTORY_DEPLOY_USERNAME)
          ARTIFACTORY_DEPLOY_PASSWORD: $(ARTIFACTORY_DEPLOY_PASSWORD)
          GITHUB_BRANCH: $(Build.SourceBranchName)
          GIT_SHA1: $(Build.SourceVersion)
        inputs:
          goals: 'deploy -P release'
          options: >-
            $(commonMavenArguments)
            --settings $(mavenSettings.secureFilePath)
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenOptions: $(MAVEN_OPTS)

    - job: runJavaUnitTests
      displayName: 'Java UTs'
      dependsOn: runJavaBuild
      workspace:
        clean: all
      steps:
      - task: DownloadSecureFile@1
        displayName: 'Download Maven settings'
        name: mavenSettings
        inputs:
          secureFile: 'maven-settings.xml'

      - powershell: |
          # Calculate the file path
          $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\scripts\version\Version.props"
          Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."

          # Read the version from the file
          [xml]$versionProps = Get-Content "$versionFilePath"
          $sonarProjectVersion = $versionProps.Project.PropertyGroup.MainVersion
          Write-Host "Sonar project version is '${sonarProjectVersion}'"

          # Set the variable to it can be used by other tasks
          Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"
        displayName: 'Read Sonar project version from the versions.props file'

      - template: update-maven-version-steps.yml
        parameters:
          mavenSettingsFilePath: $(mavenSettings.secureFilePath)

      - task: DownloadPipelineArtifact@2
        displayName: 'Download .Net binaries for Maven build'
        inputs:
          artifact: Binaries
          targetPath: 'analyzers/src/SonarAnalyzer.Vsix/bin/$(buildConfiguration)/'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download rule descriptor binaries'
        inputs:
          artifact: RuleDescriptorBin
          targetPath: 'analyzers\src\SonarAnalyzer.RuleDescriptorGenerator\bin'

      - task: SonarCloudPrepare@1
        displayName: 'Prepare code analysis for Java plugin'
        inputs:
          SonarCloud: 'SonarCloud'
          organization: 'sonarsource'
          scannerMode: 'Other'

      - task: Maven@3
        displayName: 'Maven verify, UTs with SonarCloud'
        inputs:
          goals: 'verify sonar:sonar'
          options: -B --settings $(mavenSettings.secureFilePath) -Pcoverage -Dsonar.projectVersion=$(SONAR_PROJECT_VERSION)
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'UTs on Windows'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenOptions: $(MAVEN_OPTS)
          sonarQubeRunAnalysis: true
          sqMavenPluginVersionChoice: 'latest'

      - task: SonarCloudPublish@1
        displayName: 'Code Analysis - Publish QG'
        inputs:
          pollingTimeoutSec: '300'

    - job: runJavaIntegrationTests
      displayName: 'Java ITs'
      dependsOn: runJavaBuild
      workspace:
        clean: all
      steps:
      - task: DownloadSecureFile@1
        displayName: 'Download Maven settings'
        name: mavenSettings
        inputs:
          secureFile: 'maven-settings.xml'

      - template: update-maven-version-steps.yml
        parameters:
          mavenSettingsFilePath: $(mavenSettings.secureFilePath)

      - task: DownloadPipelineArtifact@2
        displayName: 'Download .Net binaries for Maven build'
        inputs:
          artifact: Binaries
          targetPath: 'analyzers/src/SonarAnalyzer.Vsix/bin/$(buildConfiguration)/'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download rule descriptor binaries'
        inputs:
          artifact: RuleDescriptorBin
          targetPath: 'analyzers\src\SonarAnalyzer.RuleDescriptorGenerator\bin'

      - task: Maven@3
        displayName: 'Maven install'
        env:
          ARTIFACTORY_DEPLOY_USERNAME: $(ARTIFACTORY_DEPLOY_USERNAME)
          ARTIFACTORY_DEPLOY_PASSWORD: $(ARTIFACTORY_DEPLOY_PASSWORD)
        inputs:
          goals: 'clean install'
          options: >-
            $(commonMavenArguments)
            --settings $(mavenSettings.secureFilePath)
            -DskipTests=true
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenOptions: $(MAVEN_OPTS)

      - task: Maven@3
        displayName: 'Maven ITs'
        env:
          ARTIFACTORY_API_KEY: $(ARTIFACTORY_API_KEY)
          GITHUB_TOKEN: $(GITHUB_TOKEN)
        inputs:
          mavenPomFile: its/pom.xml
          goals: 'verify'
          options: -B --settings $(mavenSettings.secureFilePath)
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'ITs on Windows'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenOptions: $(MAVEN_OPTS)

- stage: promoteNugets
  displayName: Promote NuGet on repox
  dependsOn: qa
  condition: succeeded()
  jobs:
    - job: promoteRepox
      displayName: 'SonarAnalyzer.CFG.CSharp'
      steps:
        - powershell: |
            # Calculate the file path
            $versionFilePath = "$env:BUILD_SOURCESDIRECTORY\scripts\version\Version.props"
            Write-Host "Reading the Sonar project version from '${versionFilePath}' ..."

            # Read the version from the file
            [xml]$versionProps = Get-Content "$versionFilePath"
            $sonarProjectVersion = $versionProps.Project.PropertyGroup.MainVersion
            Write-Host "Sonar project version is '${sonarProjectVersion}'"

            # Set the variable to it can be used by other tasks
            Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION;]$sonarProjectVersion"
          displayName: 'Read Sonar project version from the versions.props file'

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'

        - bash: pip3 install requests

        - task: PythonScript@0
          name: promoteRepox
          inputs:
            failOnStderr: true
            scriptSource: 'inline'
            script: |
              import requests
              import os
              import sys

              version = '$(SONAR_PROJECT_VERSION).$(Build.BuildId)'
              isPr = '$(Build.Reason)' == 'PullRequest'
              sourceRepo = os.environ['ARTIFACTORY_NUGET_REPO']
              targetRepo = None
              if isPr:
                targetRepo = sourceRepo.replace('qa', 'dev')
              else:
                targetRepo = sourceRepo.replace('qa', 'public')

              artifact = f'SonarAnalyzer.CFG.CSharp.{version}.nupkg'
              print(f'Promoting nuget {artifact} from {sourceRepo} to {targetRepo}')

              url = f'$(ARTIFACTORY_URL)/api/move/{sourceRepo}/{artifact}?to=/{targetRepo}/{artifact}'
              headers = {'Content-Type': 'application/json'}
              response = requests.post(url, headers=headers, auth=('$(ARTIFACTORY_API_USER)', '$(ARTIFACTORY_API_KEY)'))

              fixedBranch = ''
              if not isPr:
                # Cannot use BUILD_SOURCEBRANCHNAME because of https://github.com/Microsoft/azure-pipelines-agent/issues/838
                branch = os.environ['BUILD_SOURCEBRANCH']
                refPrefix = "refs/heads/"
                if branch.startswith(refPrefix):
                  fixedBranch = branch[len(refPrefix):]
              print("##vso[task.setvariable variable=fixedBranch;isOutput=true]" + fixedBranch)

              promoted = response.status_code == 200
              if not promoted:
                print('[!] [{0}] Server Error'.format(response.status_code), file=sys.stderr)

    - job: nugetBurgrFailed
      dependsOn: promoteRepox
      pool: server
      condition: failed()
      steps:
      - template: notify-burgr-steps.yml@commonTemplates
        parameters:
          name: 'artifacts'
          type: 'promotion'
          status: 'failed'
          fixedBranch: $(fixedBranch)

    - job: nugetBurgrCanceled
      dependsOn: promoteRepox
      pool: server
      condition: canceled()
      steps:
      - template: notify-burgr-steps.yml@commonTemplates
        parameters:
          name: 'artifacts'
          type: 'promotion'
          status: 'canceled'
          fixedBranch: $(fixedBranch)

- template: promote-stage.yml@commonTemplates
  parameters:
    stageName: 'Artifacts:'
    stageDependencies:
    - promoteNugets
