
pool: '.Net Bubble - GCP'

stages:
- stage: Debug
  displayName: Debug
  jobs:
  - job: ListFiles
    displayName: 'List Files'

    steps:
    - script: 'cd analyzers\src & dir /S'
      displayName: "List files"
