schedules:
# Run from Monday to Friday at 5:30 UTC (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#cron-syntax)
- cron: "30 5 * * 1-5"
  displayName: Daily build
  branches:
    include:
    - master
    - branch-*
  always: true

trigger:
- master
- branch-*

pool: .net-bubble-aws-re-team-prod

variables:
  - group: sonar-dotnet-variables
  - group: sonarsource-build-variables
  - group: artifactory_access
  - group: digicert-keylocker
  # ARTIFACTORY_URL https://repox.jfrog.io/repox => https://repox.jfrog.io/artifactory
  # JFROG_URL https://repox.jfrog.io
  # https://github.com/SonarSource/parent-oss/blob/master/pom.xml#L708-L711
  - name: ARTIFACTORY_DEPLOY_USERNAME
    value: $[variables.ARTIFACTORY_QA_DEPLOYER_USERNAME]
  # ~https://github.com/SonarSource/re-ci-images/blob/master/docker/mvn/settings-private.xml
  - name: ARTIFACTORY_PRIVATE_USERNAME
    value: $[variables.ARTIFACTORY_PRIVATE_READER_USERNAME]
  - name: ARTIFACTORY_QA_READER_USERNAME
    value: $[variables.ARTIFACTORY_PRIVATE_READER_USERNAME]
  # pipelines-yaml-templates/promote-stage.yml line 56
  - name: ARTIFACTORY_API_USER
    value: $[variables.ARTIFACTORY_PROMOTER_USERNAME]
  - name: ARTIFACTORY_API_KEY
    value: $[variables.ARTIFACTORY_PROMOTER_ACCESS_TOKEN]
  - name: UnitTestProjectPath
    value: 'analyzers\tests\SonarAnalyzer.Test\'
  - name: UnitTestResultsPath
    value: '$(Build.SourcesDirectory)\TestResults'
  - name: CoveragePath
    value: '$(Build.SourcesDirectory)\coverage'
  - name: UnitTestExclusionsPattern
    value: 'analyzers/tests/SonarAnalyzer.Test/TestCases/**/*'
  - name: isReleaseBranch
    value: ${{ or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/branch-')) }}
  - name: vsVersion
    value: '17.0'

resources:
  repositories:
    - repository: pipelines-yaml-templates
      type: git
      name: pipelines-yaml-templates
      ref:  refs/tags/v3.0.0


  - job: dotNetAnalysis
    displayName: '.Net Analysis'
    workspace:
      clean: all
    # This job runs the .Net code analysis and uploads to SonarCloud the test results and coverage reports generated
    # in previous jobs.
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install NuGet"

    - template: set-azp-variables-steps.yml@pipelines-yaml-templates

    - powershell: .\scripts\Mend\Mend-Scan.ps1
      displayName: "Mend scan"
      condition: eq(variables.isReleaseBranch, 'True')
      env:
        WS_PRODUCTNAME: '$(MEND_PRODUCTNAME)'
        WS_APIKEY: '$(MEND_APIKEY)'
        BUILD_NUMBER: '$(Build.BuildId)'
        GIT_SHA: '$(Build.SourceVersion)'
