pool:
  vmImage: 'windows-latest'

stages:
- stage: test
  displayName: Check dotnet version
  jobs:
    - job: check_dotnet_version
      displayName: 'Check dotnet version'
      workspace:
        clean: all
      steps:
        - task: PowerShell@2
          displayName: 'First VsWhere'
          inputs:
            targetType: 'inline'
            script: | 
              cd c:\
              vswhere.exe -all 
            
        - task: PowerShell@2
          displayName: 'dotnet build version'
          inputs:
            targetType: 'inline'
            script: dotnet build --version

        - task: PowerShell@2
          displayName: 'First MsBuild version'
          inputs:
            targetType: 'inline'
            script: . "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" -version

        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.x'

        - task: PowerShell@2
          displayName: 'Second VsWhere'
          inputs:
            targetType: 'inline'
            script: |
              cd c:\
              vswhere.exe -all 

        - task: PowerShell@2
          displayName: 'dotnet build version'
          inputs:
            targetType: 'inline'
            script: dotnet build --version

        - task: PowerShell@2
          displayName: 'Second MsBuild version'
          inputs:
            targetType: 'inline'
            script: . "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" -version