# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'sonaranalyzer-dotnet/SonarAnalyzer.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: "Install nuget"

- task: NuGetCommand@2
  displayName: "Restore nuget packages"
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build SonarAnalyzer"
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: "Run SonarAnalyzer unit tests"
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\**\*.UnitTest.dll
     !**\obj\**
    runInParallel: true
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    rerunFailedTests: false
