name: Create Pull Request

on:
  pull_request:
    types: ["opened"]

jobs:
  assign_and_create_card:
    name: Assign issue to sender and create Kanban card
    runs-on: ubuntu-latest
    # PRs from forks don't have required token authorization
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      # https://github.com/actions/github-script
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const IN_PROGRESS_COLUMN = 4971952;
            //
            async function addAssignee(issue, login) {
                console.log("Assigning to: " + login);
                await github.issues.addAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    assignees: [login]
                });
            }
            //
            if(context.payload.pull_request.body.match(/Fixes\s*#\d+/gi)) {
                console.log("Skip, contains 'Fixes'");  // There should already be a card with original issue
            } else {
                addAssignee(context.payload.pull_request, context.payload.sender.login);
                github.projects.createCard({ column_id: IN_PROGRESS_COLUMN, content_id: context.payload.pull_request.id, content_type: "PullRequest" });
                console.log("Done");
            }